# Generated by Django 2.1.1 on 2020-01-23 02:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
