# Generated by Django 2.1.1 on 2020-01-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200124_2139'),
        ('accounts', '0002_auto_20200123_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='main.Chat'),
        ),
    ]
