# Generated by Django 2.1.1 on 2020-01-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, to='main.Chat'),
        ),
    ]
