# Generated by Django 2.1.1 on 2020-01-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200125_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='main.Chat'),
        ),
    ]
