# Generated by Django 2.1.1 on 2020-01-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200128_1938'),
        ('accounts', '0007_auto_20200125_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.AddField(
            model_name='user',
            name='chatrooms',
            field=models.ManyToManyField(blank=True, to='main.ChatRoom'),
        ),
    ]
