# Generated by Django 2.1.1 on 2020-01-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbox',
            old_name='chat_room',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_chat',
        ),
    ]
