# Generated by Django 2.1.1 on 2020-01-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200124_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatbox',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatbox',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.AddField(
            model_name='chat',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChatBox',
        ),
        migrations.AddField(
            model_name='chat',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ChatRoom'),
        ),
    ]
